### ISSUE TITLE
Ability to see more info about folders or files in default view.

### ISSUE THREAD

**Issue by thepenguinthatwants** [dylanaraps/fff#63]
Right now its only one click away (x) but I am wondering if in the default view we can customize fff to show more info.. like an auto-updating info about file size like in nnn? Or seeing the rights of the file.

**Comment by Frago9876543210** [comment]
It would be nice to show the size of files, etc.

**Comment by dylanaraps** [comment]
There's no method of grabbing file size in pure bash (*bash is aware of file size internally, however scripts can't access this information*). As for file permissions, scripts can partially grab the information (*file permissions can be retrieved for current user only*).

See this example script (`usage: script path`):

```sh
#!/usr/bin/env bash
#
# Show file perms in pure bash.

file="${1:-${HOME}/dotfiles}"

[[ -r $file ]] && r="r"
[[ -w $file ]] && w="w"
[[ -x $file ]] && x="x"

printf '%s\n' "$file: ${r:--}${w:--}${x--}"
```

Example output:

```sh
➜ perms /
/: r-x
➜ perms ~
/home/black: rwx
➜ perms /usr/share/alsa/
/usr/share/alsa/: r-x
```

Would this permissions output suffice? The idea is to show it in the `status_line` for the current file (*to not clutter the file list*).

**Comment by Frago9876543210** [comment]
Size can be obtained through `du -sh file`

**Comment by dylanaraps** [comment]
I'm aware. I'm referring to a pure bash method of retrieving the information. Using `du -sh` on every file in the list would noticeably slow `fff` down. The `-h` flag is also non-POSIX which would require `fff` to convert the size to a human readable format every-time an item line is printed. 

I have this working locally and the delay both visually and latency-wise is too large to make this feature worthwhile. I've optimized the `du` call to once per directory read. The only issue is optimizing the `print_line` function since accessing the file information (*which is stored in an array with a matching index*) is rather slow.

**Comment by dylanaraps** [comment]
I have file size working in this PR: https://github.com/dylanaraps/fff/pull/95

Try it out and let me know how it works for you. 

Note: File size conversion from bytes is currently lazy. I'm sill working on full conversion.

**Comment by dylanaraps** [comment]
I've changed my mind and this won't be added. `fff` will stay as minimal as possible due to time constraints in my life. This may be revisited at some point. #95 will stay open.
